name: Env

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to run the workflow on'

env:
  MY_SECRET: ${{ secrets.MY_SECRET }}
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables
        run: |
          echo "MY_SECRET: $MY_SECRET"
          echo "NODE_ENV: $NODE_ENV"

      - name: Run shell command    
        run: |
          echo "Run successful!!"

